<a href="https://colab.research.google.com/github/Noxira/doremonangis/blob/main/Bismillah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [152]:
import numpy as np
import matplotlib.pyplot as plt

import pywt
import pywt.data

In [90]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [91]:
#check the number of dimension
scalar.ndim

0

In [92]:
#create a vector
vector = tf.constant([10])
vector.ndim

1

In [93]:
#check the dimension of vector
vector.ndim

1

In [94]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [95]:
matrix.ndim

2

In [96]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                             [8.,9.]], dtype = tf.float16)
another_matrix #specify the data type with dtype parameter
#lower number on data dtye, lower memory required to store the number in the computer

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [97]:
#number of dimension
another_matrix.ndim

2

In [98]:
#let's create tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [99]:
tensor.ndim

3

what we've created so far :
* scalar : single number
* vector : a number with direction (e.g wind speed and direction)
* matrix : a 2-dimensional array of number
* tensor : an n-dimensional array of numbers (when n can be any number)

### Creating tensors with 'tf.variable'

In [100]:
#Cretae the same tensor with tf variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [117]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [116]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [153]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor
#just unchangeable


AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size with random number


In [119]:
# create two random (but the same) tensors
random_l = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_l = random_l.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_l, random_2, random_l == random_2

#Are they equal


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [120]:
### shuffle the order of element in a tensor (valuable for when you want to shuffle your data, so the inherent order doesn't affect the learning activity)
not_shuffle = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffle.ndim
# shuffle
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [121]:
# shuffle  read juga : https://www.tensorflow.org/api_docs/python/tf/random/set_seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [122]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'


tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [123]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed = 42)

## if we want our shuffle tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [124]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [125]:
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy array into tensors
the main difference between the two of them if that tensors can be run on a GPU (much faster for numerical computing)

In [126]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create numpy array between 1 and 25
numpy_A
#x = tf.constant(matrix)
#y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [127]:
A = tf.constant(numpy_A, shape =(2,3,4)) #the total of new shape must equal to numpy's original shape
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensor
* shape = tensor.shape
* rank = tensor.ndim
* axis or dimension = tensor[0], etc
* size

In [128]:
#ceate a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [129]:
rank_4_tensor[0][1],
rank_4_tensor.shape, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [130]:
print(rank_4_tensor.dtype)
print(rank_4_tensor.ndim)
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor).numpy()) #using numpy if we don't want tensor type

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120


### Indexing tensors

It can be indexed just like python list

In [131]:
rank_4_tensor[:1,:1,:,:1]#Get the first two elements of each dimension of our 4 rank tensors
rank_4_tensor[:1,:2,:3,:2]

<tf.Tensor: shape=(1, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [132]:
#Get the first elemen from each dimension from each index  except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [133]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [134]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
some_list = [1,2,3,4]
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [135]:
#get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [136]:
# add in extra dimension
rank_3_tensor =rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [137]:
tf.expand_dims(rank_2_tensor,axis = 2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensor[link text]
Basic operation

In [138]:
#Can add values to a tensor using addition operation
tensor = tf.constant([[10,7],[3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [141]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [142]:
#Multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [143]:
#can use the tensorflow build-in function to
tf.multiply(tensor,10) #lebih cepet kalau pakai fungsi tensorflow

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication
Important in machine learning, rules :
* inner dimension must be same
* the result will have same dimension with outer dimension


In [139]:
#matrix mutlipication

print(tensor)
print(tf.matmul(tensor,tensor))
tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [144]:
# matrix multiplication with python
tensor @ tensor
tensor.shape


TensorShape([2, 2])

In [105]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7,8],
                 [8,9],
                 [10,11]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 8,  9],
        [10, 11]], dtype=int32)>)

In [104]:
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  8],
       [ 9, 10, 11]], dtype=int32)>

In [103]:
x.shape, tf.reshape(y,shape=(2,3)).shape
print(tf.reshape(y,shape=(2,3)).shape)

(2, 3)


In [102]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  28,  30],
       [ 57,  64,  68],
       [ 89, 100, 106]], dtype=int32)>

In [88]:
#can do the same with transpose
x,tf.transpose(x), tf.reshape(x,shape=(2,3)) #transpose -> tukar axis, reshape, ngatur isi tensor supaya sesuai dengan shape baru

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [145]:
# try matrix mutlipication with transpose
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

**The dot product**
Can perform matrix multiplication using :
* tf.matmul()
* tf.tensordot()


In [146]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 8,  9],
        [10, 11]], dtype=int32)>)

In [150]:
tf.transpose(x),y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 8,  9],
        [10, 11]], dtype=int32)>)

In [163]:
#perform dot product requires x or y to be transposed
tf.tensordot(tf.transpose(x),y,axes=[[1], [0]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

In [159]:
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 81,  90],
       [106, 118]], dtype=int32)>

In [158]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  26,  32],
       [ 53,  60,  74],
       [ 83,  94, 116]], dtype=int32)>

In [157]:
tf.matmul(x,tf.reshape(y,shape =(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 25,  28,  30],
       [ 57,  64,  68],
       [ 89, 100, 106]], dtype=int32)>

In [164]:
#check the values of y, reshape y, and transposed y
print("Normal Y :")
print(y,"\n")
print("Y reshaped to(2,3):")
print(tf.reshape(y,(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(y,),"\n")

Normal Y :
tf.Tensor(
[[ 7  8]
 [ 8  9]
 [10 11]], shape=(3, 2), dtype=int32) 

Y reshaped to(2,3):
tf.Tensor(
[[ 7  8  8]
 [ 9 10 11]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  8 10]
 [ 8  9 11]], shape=(2, 3), dtype=int32) 



### Change the datatype of sensor


In [165]:
tf.__version__

'2.12.0'

In [166]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4]) #faster running operation with lower bit precision
B = tf.constant([7,10])
B.dtype

tf.float32

In [173]:
#change dtype to 16 bit precision
D = tf.cast(B, dtype=tf.float16)
D.dtype
E = tf.cast(B, dtype=tf.float32)
print(E.dtype)


<dtype: 'float32'>


### Aggregating tensors

equals to condensing them from multiple values down to a smaller amount of value

In [174]:
# Get the absolute value
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [175]:
F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 5, 80, 95, 96, 79, 26, 84, 74, 64, 25,  8, 16, 37, 71, 39, 35,  9,
       78,  1, 18, 57, 34, 85, 55, 39, 46, 85, 57,  4, 94, 91, 77, 55, 35,
       31, 14, 20, 18, 25, 70, 55,  1, 19, 49, 73, 54, 92,  3, 35,  9])>

In [176]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [177]:
tf.reduce_min(F) #Same with mean, max, and sum

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [178]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2322>

In [182]:
import tensorflow_probability as tfp
#Variance
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=885>

In [181]:
tf.math.reduce_std(tf.cast(F, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.753765>

In [ ]:
tf.math.reduce_std

In [184]:
tf.math.reduce_variance(tf.cast(F, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=885.2865>

In [187]:
#Find positional max and min
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

In [188]:
tf.argmax(G) #tf.argmin()

<tf.Tensor: shape=(), dtype=int64, numpy=33>

In [190]:
#INDEX ON OUR LARGEST VALUE
assert G[tf.argmax(G)] == tf.reduce_max(G)

### Squeezing tensors

In [204]:
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [196]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [202]:
H_squeezed = tf.squeeze(H)
H_squeezed , H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [206]:
### One hot encoding
#create a list of indices
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [213]:
I = tf.range(1,10)
I
tf.square(I)
tf.sqrt(tf.cast(I, dtype=(tf.float32)))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [214]:
tf.math.log(tf.cast(I, dtype=(tf.float32)))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [221]:
#create a tensors directly from a numpy array
J = tf.constant(np.array([3.,7.,10.]))
J[0]

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [219]:
# Convert back
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [222]:
J.numpy()[0],type(np.array(J))

(3.0, numpy.ndarray)

In [ ]:
J = tf.constant([3.])

In [224]:
numpy_J = tf.constant(np.array([3,7,10]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype, tensor_J.dtype

(tf.int64, tf.float32)

### Regression Ploblem
Predicting a number of some sort, such as trying to predict the coordinates of where the boxes should be in an object detecion problem
